"""Risk service - heuristic risk scoring and decision engine."""
from __future__ import annotations

from app.models import Asset, RiskAssessment

WEIGHT_AGE = 0.30
WEIGHT_MAINTENANCE = 0.30
WEIGHT_STATUS = 0.25
WEIGHT_USAGE = 0.15

STATUS_SCORES: dict[str, float] = {
    "operational": 0.0,
    "degraded": 35.0,
    "critical": 70.0,
    "offline": 90.0,
}

USAGE_SCORES: dict[str, float] = {
    "low": 0.0,
    "medium": 15.0,
    "high": 30.0,
}

RISK_LEVELS = [
    (30, "low"),
    (65, "medium"),
    (85, "high"),
    (101, "critical"),
]


def _risk_level(score: float) -> str:
    for threshold, level in RISK_LEVELS:
        if score < threshold:
            return level
    return "critical"


def recommend_action(risk_score: float, status: str) -> dict:
    """Return a recommended action and estimated cost based on risk score."""
    if risk_score < 30:
        return {"action": "monitor", "cost_estimate_usd": 500}
    elif risk_score < 65:
        return {"action": "maintenance required", "cost_estimate_usd": 2500}
    else:
        return {"action": "replace system", "cost_estimate_usd": 12000}


def calculate_risk(asset: Asset) -> RiskAssessment:
    """Compute a heuristic risk assessment for the given asset.

    Factors:
    - age_years: older assets carry higher risk (up to 20 years)
    - days_since_maintenance: longer gaps increase risk (up to 730 days)
    - status: operational=low, degraded=medium, critical=high, offline=very high
    - usage_level: higher usage increases wear
    """
    age_component = min(asset.age_years / 20.0, 1.0) * 100.0
    maint_component = min(asset.days_since_maintenance / 730.0, 1.0) * 100.0
    status_component = STATUS_SCORES.get(asset.status.lower(), 50.0)
    usage_component = USAGE_SCORES.get(asset.usage_level.lower(), 15.0)

    raw_score = (
        WEIGHT_AGE * age_component
        + WEIGHT_MAINTENANCE * maint_component
        + WEIGHT_STATUS * status_component
        + WEIGHT_USAGE * usage_component
    )
    risk_score = max(0.0, min(100.0, raw_score))

    confidence = 0.95
    if asset.days_since_maintenance > 1095:
        confidence -= 0.15
    if asset.status == "offline" and asset.days_since_maintenance < 30:
        confidence -= 0.10
    confidence = max(0.60, confidence)

    level = _risk_level(risk_score)
    action_info = recommend_action(risk_score, asset.status)

    recommendation = (
        f"Action: {action_info['action'].title()}. "
        f"Asset is {asset.age_years:.1f} years old with "
        f"{asset.days_since_maintenance} days since last maintenance."
    )

    return RiskAssessment(
        asset_id=asset.id,
        risk_score=round(risk_score, 2),
        confidence=round(confidence, 2),
        risk_level=level,
        recommendation=recommendation,
        estimated_cost_usd=action_info["cost_estimate_usd"],
        data_source="heuristic_model_v1",
        disclaimer=(
            "This risk score is generated by a heuristic model using available "
            "field data. It is intended to support—not replace—expert engineering "
            "judgement. Always validate with on-site inspection before action."
        ),
    )
